backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pictures"
    label: "Uploaded Pictures"
    folder: "content/pictures"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - { label: "የመስክ ፎቶዎች", value: "የመስክ ፎቶዎች" }
          - { label: "Portrait", value: "portrait" }
          - { label: "ክርስትና", value: "ክርስትና" }
          - { label: "ሽምግልና", value: "ሽምግልና" }
          - { label: "ሰርግ", value: "ሰርግ" }
          - { label: "Other", value: "other" }
        required: true
      - label: "New Category Name"
        name: "new_category"
        widget: "string"
        required: false
        hint: "Only fill this if the selected category is 'Other'."
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
      - label: "Image File (WEBP)"
        name: "image"
        widget: "image"
        required: true
        media_library:
          allow_multiple: false
